services:
  apiserver-backend:
    build:
      context: api-server/.
      dockerfile: Dockerfile
    ports:
      - "1781:1781"
    depends_on:
      - apiserver-database
    environment:
      LOG_FOLDER: logs/
      MS_API_CONFIG_PATH: /app/config/test/config.yml #TODO как то прокинуть тест/прод
      DB_USER: ${MS_APISERVER_DB_USER}
      DB_PASS: ${MS_APISERVER_DB_PASS}
      DB_NAME: ${MS_APISERVER_DB_NAME}
      YAS3_KEY: ${MS_APISERVER_YAS3_KEY}
      YAS3_SECRET: ${MS_APISERVER_YAS3_SECRET}
      PASS_SALT: "SALT"
      AWS_REGION: "ru-central1"
    volumes:
      - ./api-server/logs:/app/logs


  apiserver-database:
    restart: always
    hostname: database
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: ${MS_APISERVER_DB_USER}
        POSTGRES_PASSWORD: ${MS_APISERVER_DB_PASS}
        POSTGRES_DB: ${MS_APISERVER_DB_NAME}
    volumes:
      - db:/var/lib/postgresql/data


volumes:
  db:
